def print_block_options():
    print("AIR                   0\n\
        STONE                 1\n\
        GRASS                 2\n\
        DIRT                  3\n\
        COBBLESTONE           4\n\
        WOOD_PLANKS           5\n\
        SAPLING               6\n\
        BEDROCK               7\n\
        WATER_FLOWING         8\n\
        WATER                 8\n\
        WATER_STATIONARY      9\n\
        LAVA_FLOWING         10\n\
        LAVA                 10\n\
        LAVA_STATIONARY      11\n\
        SAND                 12\n\
        GRAVEL               13\n\
        GOLD_ORE             14\n\
        IRON_ORE             15\n\
        COAL_ORE             16\n\
        WOOD                 17\n\
        LEAVES               18\n\
        GLASS                20\n\
        LAPIS_LAZULI_ORE     21\n\
        LAPIS_LAZULI_BLOCK   22\n\
        SANDSTONE            24\n\
        BED                  26\n\
        COBWEB               30\n\
        GRASS_TALL           31\n\
        WOOL                 35\n\
        FLOWER_YELLOW        37\n\
        FLOWER_CYAN          38\n\
        MUSHROOM_BROWN       39\n\
        MUSHROOM_RED         40\n\
        GOLD_BLOCK           41\n\
        IRON_BLOCK           42\n\
        STONE_SLAB_DOUBLE    43\n\
        STONE_SLAB           44\n\
        BRICK_BLOCK          45\n\
        TNT                  46\n\
        BOOKSHELF            47\n\
        MOSS_STONE           48\n\
        OBSIDIAN             49\n\
        TORCH                50\n\
        FIRE                 51\n\
        STAIRS_WOOD          53\n\
        CHEST                54\n\
        DIAMOND_ORE          56\n\
        DIAMOND_BLOCK        57\n\
        CRAFTING_TABLE       58\n\
        FARMLAND             60\n\
        FURNACE_INACTIVE     61\n\
        FURNACE_ACTIVE       62\n\
        DOOR_WOOD            64\n\
        LADDER               65\n\
        STAIRS_COBBLESTONE   67\n\
        DOOR_IRON            71\n\
        REDSTONE_ORE         73\n\
        SNOW                 78\n\
        ICE                  79\n\
        SNOW_BLOCK           80\n\
        CACTUS               81\n\
        CLAY                 82\n\
        SUGAR_CANE           83\n\
        FENCE                85\n\
        GLOWSTONE_BLOCK      89\n\
        BEDROCK_INVISIBLE    95\n\
        STONE_BRICK          98\n\
        GLASS_PANE          102\n\
        MELON               103\n\
        FENCE_GATE          107\n\
        GLOWING_OBSIDIAN    246\n\
        NETHER_REACTOR_CORE 247")

print(print_block_options())
